/** Curated list of major Indian cities/towns for autocomplete suggestions.
 *  Kept as a flat static array (not fetched) so filtering stays instant. */
export const INDIAN_CITIES: string[] = [
  'Agra', 'Ahmedabad', 'Aizawl', 'Ajmer', 'Akola', 'Aligarh', 'Allahabad (Prayagraj)',
  'Alwar', 'Amaravati', 'Ambala', 'Ambattur', 'Amritsar', 'Anand', 'Anantapur',
  'Asansol', 'Aurangabad', 'Bagalkot', 'Balasore', 'Bally', 'Bangalore (Bengaluru)',
  'Bareilly', 'Bathinda', 'Belgaum (Belagavi)', 'Bellary (Ballari)', 'Berhampur',
  'Bhagalpur', 'Bharatpur', 'Bharuch', 'Bhavnagar', 'Bhilai', 'Bhilwara', 'Bhiwandi',
  'Bhopal', 'Bhubaneswar', 'Bikaner', 'Bilaspur', 'Bokaro', 'Chandigarh', 'Chandrapur',
  'Chennai', 'Coimbatore', 'Cuttack', 'Darbhanga', 'Davanagere', 'Dehradun', 'Delhi',
  'Dewas', 'Dhanbad', 'Dharamshala', 'Dhule', 'Dibrugarh', 'Dindigul', 'Durgapur',
  'Eluru', 'Erode', 'Faridabad', 'Firozabad', 'Gandhidham', 'Gandhinagar', 'Gangtok',
  'Gaya', 'Ghaziabad', 'Goa (Panaji)', 'Gorakhpur', 'Gulbarga (Kalaburagi)', 'Guntur',
  'Gurgaon (Gurugram)', 'Guwahati', 'Gwalior', 'Haldwani', 'Haridwar', 'Hisar',
  'Hosur', 'Howrah', 'Hubli-Dharwad', 'Hyderabad', 'Imphal', 'Indore', 'Itanagar',
  'Jabalpur', 'Jaipur', 'Jalandhar', 'Jalgaon', 'Jamnagar', 'Jamshedpur', 'Jhansi',
  'Jodhpur', 'Jorhat', 'Junagadh', 'Kadapa', 'Kakinada', 'Kalyan-Dombivli', 'Kanpur',
  'Karimnagar', 'Karnal', 'Katni', 'Kochi (Cochin)', 'Kolhapur', 'Kolkata', 'Kollam',
  'Kota', 'Kottayam', 'Kozhikode (Calicut)', 'Kurnool', 'Latur', 'Lucknow', 'Ludhiana',
  'Madurai', 'Mahesana', 'Malegaon', 'Mangalore (Mangaluru)', 'Mathura', 'Meerut',
  'Mira-Bhayandar', 'Mohali', 'Moradabad', 'Mumbai', 'Muzaffarnagar', 'Muzaffarpur',
  'Mysore (Mysuru)', 'Nadiad', 'Nagercoil', 'Nagpur', 'Naihati', 'Nanded', 'Nashik',
  'Navi Mumbai', 'Nellore', 'New Delhi', 'Noida', 'Ongole', 'Palakkad', 'Panipat',
  'Panchkula', 'Patiala', 'Patna', 'Pimpri-Chinchwad', 'Pondicherry (Puducherry)',
  'Porbandar', 'Pune', 'Raichur', 'Raipur', 'Rajahmundry', 'Rajkot', 'Ranchi',
  'Ratlam', 'Rewa', 'Rohtak', 'Rourkela', 'Sagar', 'Saharanpur', 'Salem', 'Sambalpur',
  'Sangli', 'Satara', 'Satna', 'Shillong', 'Shimla', 'Shimoga (Shivamogga)',
  'Sikar', 'Siliguri', 'Solapur', 'Sonipat', 'Srinagar', 'Surat', 'Surendranagar',
  'Thane', 'Thanjavur', 'Thiruvananthapuram (Trivandrum)', 'Thoothukudi (Tuticorin)',
  'Thrissur', 'Tiruchirappalli (Trichy)', 'Tirunelveli', 'Tirupati', 'Tiruppur',
  'Udaipur', 'Udupi', 'Ujjain', 'Ulhasnagar', 'Vadodara', 'Varanasi', 'Vasai-Virar',
  'Vellore', 'Vijayawada', 'Vijaypur', 'Visakhapatnam (Vizag)', 'Warangal',
  'Yamunanagar',
];
